### ISSUE TITLE
[ANDROID] Implement story view activity

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#122]
Story view activity is an activity which will take a story id. After that it will retrieve all details about the story and its comments.

The comment API is not written yet, but we can add a RecyclerView which shows dummy data.

**Comment by fthdgn** [comment]
Story view activity should be improved.

The activity should consist these:
- Story title
- Story content
- Clickable owner name. It will open user page.
- Clickable last editor name. It will open user page.
- Last edit date
- Creation date
- Report button (it could be on action bar)
- Positive vote button
- Negative vote button
- A section where the media of the story will be listed.
- Comment section. #138

**Comment by empaksoy** [comment]
I implement comment part. It is almost done I think.

**Comment by fthdgn** [comment]
I have written most of the code with recycler view.
There is some point which is missing.
Like dislilke buttons, report menu item, edit menu item
If you will do these let me know. Otherwise I will write them also.
