### ISSUE TITLE
[ANDROID] Profile page activity

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#124]
An activity where user view his/her own or other users' profile.
- Username
  - If own page, edit option.
- Email address
  - Only if own page. Edit
- Change password
  - Only if own page
- Notification setting
  - Only if own page
- Owned stories
- Followed stories
- Followed users
- Users who follow the user
- Follow/unfollow button
  - If not own page

**Comment by fthdgn** [comment]
Own profile page of the user is now on MainActivity. Profile edit options are removed from this activity.
The only thing we should consider while creating this activity, if the user is himself we should disable follow button.

**Comment by fthdgn** [comment]
What is the status of this activity.

**Comment by ceenk** [comment]
working on it right now
