### ISSUE TITLE
[REST] /user/update

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#129]
Updates the information of the user.
- Access token is required. The information can be changed by user himself/herself.

Required Request content
- **TEXT password_old** old password

Optional Request content
- **TEXT username** new username
- **TEXT password_new** new password
- **TEXT email** new email
- **TEXT fullname** new fullname

Expected Response content
- LoginResponse

**Comment by gmzrmks** [comment]
please review and if it is not ok reopen the issue.

**Comment by fthdgn** [comment]
Access token is not send on request body, it is on header. There is a usage example on /story/create
There should be syntax check on username and email address also. There is an usage example on /user/register

**Comment by gmzrmks** [comment]
fixed with 37e8769
