### ISSUE TITLE
[REST] /user/follow

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#130]
Follows and unfollows an user
- Access token is required.

Required Request content
- **LONG user_id** user id of the user will be followed
- **BOOLEAN is_follow** Whether it is follow or unfollow

Expected Response content
- Success/Failure

**Comment by bilalyasar** [comment]
closed via https://github.com/bounswe/bounswe2015group7/commits/master

**Comment by fthdgn** [comment]
Access token is not on request body. İt is on header.

**Comment by bilalyasar** [comment]
thanks 
fixed
https://github.com/bounswe/bounswe2015group7/commit/056aa3d71491392db7dec9381874103f9ab6c632
