### ISSUE TITLE
[REST] /user/get

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#131]
Gets public information of the user

Required Request content
- **LONG user_id** user id of the user will be followed

Expected Response content
- **STRING username**
- *_LONG user_id *_
- **STRING fullname**

**Comment by bilalyasar** [comment]
closed via https://github.com/bounswe/bounswe2015group7/commit/7810b4231e59ded27fa5bb44a5ed360849510d45

**Comment by fthdgn** [comment]
I think we should not use LoginResponse. This method is called by other users.

**Comment by bilalyasar** [comment]
is it important?
do we need create class for every combination?

**Comment by bilalyasar** [comment]
after discussing with @fthdgn , we think that there is no need to crate new class for every combination. It is not fully needed for simplicity. So i am closing this issue.
