### ISSUE TITLE
[REST] /user/stories

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#132]
Gets a list of stories of the user

Required Request content
- **LONG user_id** user id of the owner.

Optional Request content
- **INT page** Page of the results default 1
- **INT size** Size of the page, default 10

Expected Response content
- SearchResponse

**Comment by bilalyasar** [comment]
done https://github.com/bounswe/bounswe2015group7/commit/c023b7136a621406ffbcd3cf4b4225783a35444e
