### ISSUE TITLE
[REST] comment/get

### ISSUE THREAD

**Issue by bulenthacioglu** [bounswe/bounswe2015group7#135]
Gets comment according to the id
Required Request content
- **LONG comment_id** id of the comment

Expected Response content
- **LONG story_id**
- **LONG owner_id**
- **DATE create_date** 
- **STRING content**
- **DATE last_edit_date**

**Comment by bulenthacioglu** [comment]
Done

**Comment by fthdgn** [comment]
I think we should add username of the owner. It is always required for displaying as in the /story/get

**Comment by bilalyasar** [comment]
closed via https://github.com/bounswe/bounswe2015group7/commit/38830ce388018044e6864e410694347bc95a26c5
