### ISSUE TITLE
[REST] comment/list

### ISSUE THREAD

**Issue by bulenthacioglu** [bounswe/bounswe2015group7#136]
Gets the list of the comments of a story
Required Request content
- **LONG story_id** id of the story

Expected Response content
- **LIST comments**

**Comment by bulenthacioglu** [comment]
Done

**Comment by fthdgn** [comment]
I think we should add pages on this function as in the search function.

**Comment by fthdgn** [comment]
I think the comments should return from newest to oldest.

**Comment by bulenthacioglu** [comment]
Done

**Comment by fthdgn** [comment]
It is sorting only the results which has returned from database. It should sort on database query.
