### ISSUE TITLE
[REST] /story/report

### ISSUE THREAD

**Issue by bilalyasar** [bounswe/bounswe2015group7#139]
required
id

result:

success or fail

and update the database

**Comment by bilalyasar** [comment]
@gmzrmks  i will assign to you another issue.

**Comment by fthdgn** [comment]
- This function requires a registered user. There should be access_token check to retrieve user.
- We don't request user_idf from user. Request access token and retrieve user from it.
- Reporting mechanism does not check previous report of the user.
  - We should create a new relation table with two column, user_id,story_id
  - Each report also placed in table to check previous reports..

**Comment by bilalyasar** [comment]
fixed https://github.com/bounswe/bounswe2015group7/commit/e4768db03bf999b27461cc9a29afc29b7ee915a8
