### ISSUE TITLE
[REST]  /story/report

### ISSUE THREAD

**Issue by bilalyasar** [bounswe/bounswe2015group7#144]
request: user-id , story-id

action: update the table

**Comment by bilalyasar** [comment]
closed via https://github.com/bounswe/bounswe2015group7/commit/bbc6f4be6b78e5741ea360a8a1789723f2793227

**Comment by fthdgn** [comment]
I think we should not sent user-id, the user id should be retrieved by using access-token

**Comment by fthdgn** [comment]
This request is not working.

Request
{
"story_id" : 1,
"user_id":1
}

response
{
  "timestamp": 1449955965244,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.dao.DataIntegrityViolationException",
  "message": "could not execute statement; SQL [n/a]; constraint [PRIMARY]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement",
  "path": "/story/report"
}

**Comment by bilalyasar** [comment]
fixed also added test https://github.com/bounswe/bounswe2015group7/commit/88b0c01d49594a54750c8ee472e9949a46c938ef
