### ISSUE TITLE
[REST] /story/vote

### ISSUE THREAD

**Issue by bilalyasar** [bounswe/bounswe2015group7#145]

**Comment by gmzrmks** [comment]
done.

**Comment by fthdgn** [comment]
- up_or_down_vote on request body is Boolean and it is not clear what true is and what false is. The name can be changed to is_positive
- This function requires a registered user. There should be access_token check to retrieve user.
- Voting mechanism does not controller previous vote of the user.
  - We should create a new relation table with three column, user_id story_id vote_is_positive
  - Each vote also placed in table to check previous votes.

P.S Please don't write everything on single line. It is not readable.

**Comment by fthdgn** [comment]
The controller is not working.

Request
{
"story_id" : 1,
"user_id":1,
"isPositive" : true
}

Response
{
  "timestamp": 1449958911268,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.dao.InvalidDataAccessApiUsageException",
  "message": "Not an entity:class sculture.models.tables.relations.VoteStory; nested exception is java.lang.IllegalArgumentException: Not an entity:class sculture.models.tables.relations.VoteStory",
  "path": "/story/vote"
}

**Comment by gmzrmks** [comment]
It is fixed via 082effb .

Request
{
"story_id" : 1,
"user_id":5,
"isPositive" : false
}

Response
{
  "id": 1,
  "title": "dugun",
  "creation_date": 1449396194000,
  "update_date": 1449396194000,
  "last_editor": {
    "id": 2,
    "username": "deneme12"
  },
  "owner": {
    "id": 2,
    "username": "deneme12"
  },
  "tags": [],
  "positive_vote": 1,
  "negative_vote": 2,
  "report_count": 0
}

But there is a new issue now, when a user which is already voted tries to vote a story again I got this error;
{
  "timestamp": 1450014155280,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "org.springframework.dao.DataIntegrityViolationException",
  "message": "could not execute statement; SQL [n/a]; constraint [PRIMARY]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement",
  "path": "/story/vote"
}

I am working on it now.If you have any suggestions, I would like to hear. Thanks!

**Comment by bilalyasar** [comment]
fixed via https://github.com/bounswe/bounswe2015group7/commit/5c514a962421a2943064053dd4aeb8635ad365f8
