### ISSUE TITLE
[REST] /tag/get

### ISSUE THREAD

**Issue by bilalyasar** [bounswe/bounswe2015group7#146]

**Comment by bilalyasar** [comment]
closed via https://github.com/bounswe/bounswe2015group7/commit/c66ce19be3d40d9e9e6a919fe2d737e3aa50f1df

**Comment by fthdgn** [comment]
This API should return also last editor name.

**Comment by bilalyasar** [comment]
https://github.com/bounswe/bounswe2015group7/commit/2acdb2ae1d25c2ee9ac5f87e40b8259524f933ee
