### ISSUE TITLE
[ANDROID] Tag description activity

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#147]
The activity is called by a tag_title.

Content
- Tag title
- If there is tag description
  - Tag description (it may be null)
  - Tag description last edit date and last editor username(username is clickable)
  - Edit description button on action bar menu 
  - Make description text collapsible (show more/less) for long texts
- If there is no description
  - A button with "create description"
- Tag description edit, create.
  - Make description text editable.
  - But visible save button on action bar while editing.
- Put a list of stories with this tag below with recycler view.
  - Support paged story list retrieve

**Comment by fthdgn** [comment]
What is the status on this activity?

**Comment by ceenk** [comment]
working on it
