### ISSUE TITLE
[REST] [BUG] Two different user with same email address

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#148]
Tow user can register with same email address. But non of them can login, because of the login controller find two different user with same email address and throws errors.

The User model defines email column as unique. May be hibernate is not working as we expected. We should fix this and two user should not have same email address.

**Comment by bilalyasar** [comment]
actually, defining unique in hibernate doesn't solve the problem. Because, hibernate doesn't change table. We need to make this change at database level, also i added small check.
https://github.com/bounswe/bounswe2015group7/commit/ea73d6a31a99829a8de7f01bd2ca02581ae3744e
