### ISSUE TITLE
[REST] /story/edit

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#151]
Edit a comment
- Access token is required.

Required Request content
- **LONG story_id** Comment id
  - **TEXT content** New content
  - **TEXT title** New title
  - **TEXT ARRAY tags** New tags
  - **LONG ARRAY media_ids** New media ids

**Comment by bilalyasar** [comment]
closed via https://github.com/bounswe/bounswe2015group7/commit/2bfaab8e1ce09dd9196f62c39638b254c889123d
