### ISSUE TITLE
Code Review for Assignment

### ISSUE THREAD

**Issue by gmzrmks** [bounswe/bounswe2015group7#162]
@bulenthacioglu can you please review the commit 68f0a9a and give me feedback by the end of the day?

**Comment by bulenthacioglu** [comment]
Your code is generally clear and in the same structure we use as the backend team. In the controller, you wrote two successful methods without bugs as we can do story voting and user updating. Your variable names are understandable and coherent with the database. You considered the exceptions and handled them very well. There is one thing I can criticize you, you didn't write any comment as the most of our team members. Your indentation is good and your code is easily modifiable.
About your changes in StoryDao.java, I can say pretty much the same. Your syntax and style is good. Your system of checking the vote as a boolean is pretty creative as you cannot vote a content other way from up or down, I think. Again, comments are missing though.
In UserUpdateRequestBody.java, you had a good job as well, the variable names are coherent with the update method in controller class. Style is good again, maybe you have generated setters and getters automatically in IntelliJ. We can see the success of this class by checking the user update API, it works. So you had a great job. This class is easily modifiable when done with the method in controller. Needless to say again, comments are missing.
And finally, your changes in BaseStoryResponse.java are logical. Your style is good, comments are missing.
In overall, you had a great work. You can consider running unit tests on your code and adding some comments. Also you can add documentation with Javadoc. I wish you keep up your good work, and thank you for your contribution. Regards!

**Comment by bilalyasar** [comment]
this is old issue, should be resolved already
