### ISSUE TITLE
Nullpointer exception on story/create

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#170]
Request:
{
"title": "test",
"content": "test",
"tags" : ["tag1", "tag2"]
}

Response
{
  "timestamp": 1449939489523,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "java.lang.NullPointerException",
  "message": "No message available",
  "path": "/story/create"
}

**Comment by bilalyasar** [comment]
fixed via https://github.com/bounswe/bounswe2015group7/commit/77bc86709d93f930cae3b39fae893a8188043788 also i added test so now we are sure. :)
