### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by bulenthacioglu** [bounswe/bounswe2015group7#179]
Can you review my code and give feedback? 7669fb8 @gmzrmks

**Comment by gmzrmks** [comment]
- Your code is clear and readable. 
- Your comment for each method is enough to understand what it does. 
- Naming for variables and methods is reasonable and compatible with database.
- I think the code can be easily modified by someone else.
- There are no bugs as far as I see, but if I notice something later, I will open an issue for you to fix it.
  Here are some items that you should do;
- Testing : you should write some test methods for comment dao and its controller
- Documentation
  Fyi.
