### ISSUE TITLE
Creating realistic data(use cases) for milestone 2 presentation

### ISSUE THREAD

**Issue by atakanarikan** [bounswe/bounswe2015group7#189]
We should have some realistic data while presenting instead of using "asdasdhg" or "deneme" :)

**Comment by bilalyasar** [comment]
good point :+1:

**Comment by narinmahmuti** [comment]
Noted, will come up with some :)

**Comment by narinmahmuti** [comment]
I wrote some sample user stories we can use for now, they are in the following google doc with some pictures also:
https://docs.google.com/document/d/1r2iZ5mUdnfYptxdRSYIB4VdKf4BuNr2MTmUwi_Hjico/edit?usp=sharing
