### ISSUE TITLE
/story/report is not working

### ISSUE THREAD

**Issue by atakanarikan** [bounswe/bounswe2015group7#195]
**url:**
http://52.28.216.93:9000/story/report

**request:**
{
    "story_id":4,
    "user_id": 1
}

**response:**
{
 "timestamp": 1450126160870,
 "status": 500,
 "error": "Internal Server Error",
 "exception": "org.springframework.dao.DataIntegrityViolationException",
 "message": "could not execute statement; SQL [n/a]; constraint [PRIMARY]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement",
 "path": "/story/report"
}

**Comment by fthdgn** [comment]
Closed via b0c934772360b7799921fa8887203b3e9df253f7
