### ISSUE TITLE
/search returns NullPointerException

### ISSUE THREAD

**Issue by safaorhan** [bounswe/bounswe2015group7#198]
With most of the queries, /search endpoint returns 500 Internal server error.

Example request:

`http://52.28.216.93:9000/search`

Example Requests:

``` json
{
    "query": "a"
}
```

``` json
{
    "query": "travel"
}
```

``` json
{
    "query": "house"
}
```

Response:

``` json
{
  "timestamp": 1450141560008,
  "status": 500,
  "error": "Internal Server Error",
  "exception": "java.lang.NullPointerException",
  "message": "No message available",
  "path": "/search"
}
```

**Comment by fthdgn** [comment]
The reason of this problem is the search index is not up to date with database. You can force the search index to refresh by this url. 52.28.216.93:9000/admin/search/reindex
I will make the search methods more robust.
