### ISSUE TITLE
500 Error during creation of a new story

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group7#210]
I created a new story with my user: uskudarli

After filling in the title, story, and tags and 

type Exception report

message

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.lang.NullPointerException
    com.sculture.SaveStory.doPost(SaveStory.java:36)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.47 logs.

-- Screen shot of story creation.

![storycreationerror](https://cloud.githubusercontent.com/assets/1347035/12097257/51115148-b323-11e5-9b40-8955b07ca8f5.png)

-- The picture I attached:

![kursungerme15](https://cloud.githubusercontent.com/assets/1347035/12097285/846f6494-b323-11e5-993b-8959b634df56.jpg)

-- The story doesn not show in default presentation mode. The content is:

I love ancient ruins and had been curious about the so-called Anastasian Wall remains in Trakya (Thrace) [OOPS, Cant put the location... locations are very important for cultural artifacts].
I went with a friend for an entire day and search high and low for this wall. I stopped at traditional coffee houses (kiraathane or kahve) and spoke with locals (all men, of course) about the wall. They did not know what I was talking about at first. Then they realized it was the walls they used to play on as kids, which they called "Kale" as in fort. 

Seems there were much more of the wall remains not so long ago. Alas, in the recent decades people have taken the large stones that made up the wall and used them to build houses and walls and mosques and what not. The villagers don't like these stones anymore. They want to get rid of them and use concrete instead!!! Those beautiful stones... Hard to imagine. Anyway, how can you get rid of huge stones. To make matters worse, these stones are declared as historically valuable and they can not be destroyed. So, they are grumbling.

Back to basics...

The Anastasian Wall stretched from Yalikoy (Geolocation of Yalikoy) to Silivri (Geolocation of Silivri) essentially a wall from the Black Sea to the Marmara Sea to keep invaders out.

Related material: http://anastasianwall.blogspot.com.tr/ [How can I relate material and stories to each other?]

My video: <iframe width="420" height="315" src="https://www.youtube.com/embed/7Q2R5-1b_Ec" frameborder="0" allowfullscreen></iframe>

My Pictures:

I have many picture I want to add..

---

**Comment by atakanarikan** [comment]
Hello,

This is a known bug about uploading photos from the web client. Will notify you as soon as I fix the problem.

Thank you for the feedback, much appreciated.

**Comment by atakanarikan** [comment]
Hello again,

I did fix the issue with commit ac8f6fc385c265921376e8e4879dfa85adc68321 

Will let you know after the final checks and when we deploy to the server.

Cheers!

**Comment by atakanarikan** [comment]
It's deployed. You should be able to see it know.
