### ISSUE TITLE
500 Error during creation of a new story -- without any picture attachment

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group7#211]
user: uskudarli
browser: firefox

Error message:
type Exception report

message

description The server encountered an internal error that prevented it from fulfilling this request.

exception

java.lang.NullPointerException
    com.sculture.SaveStory.doPost(SaveStory.java:36)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:647)
    javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.47 logs.

title: A cup of Turkish Coffee comes with 40 years of rememberence 

tags: coffee (no context?)   

(I actually entered with (no context?). I was expecting to see semantic context recommendations, when I enter tags. For example, coffee would give a dropdown with Beverage, Programming Environment, etc.)
## story content: )

 It seems there was a man named  Bilge who sold and made coffee. He was actually a coffee seller, but people of all walks of life would come there to have coffee, visit, and get some advice at times. His coffee was known with the bitter taste. I guess you could call it full flavored.  

One day a infidel came to his shop. It was full of people. Among all the Turks there was a Greek Captain man  in the corner smoking  a water pipe.  

The janissary announced that he was offering coffee to all the wise, kind, insightful persons, with the exception of the infidel in the corner. The captain sighed and went on smoking his pipe.  

The wise owner of the shop made coffee as asked. After serving the coffee  he made a couple of more cups and went to sit and have some coffee with the captain.  

The janissary exclaimed, "Hey! Didn't I say except the infidel?"  

The wise man said this is my offering not yours. He went on visiting with the Captain for a good long time. The Captain was so impressed that he entered this event in his journal.  

Years go by... 40 years to be exact. There are Greek uprisings in Samos island. The Wise man, being included in the janissaries is stationed in Samos and is captured during the uprising. The captured slaves are sold to gain some income and most are killed. An old man pays a good price for our wise coffee seller puts him in his service. He takes him to a secluded area. The Captain remembers the coffee seller, but the wise man does not remember the captain.  

The captain says: Oh wise man, the coffee you have offered me  has created a bond that has lasted for 40 years. Even if you have forgotten, I have not. You are a free man. However, if you wish I can take you to your homeland safely.  

---

So it goes...  

Coffee among people are said to make friends, forget animosities, .... Important events and agreements are marked with drinking coffee. When a boy asks for a bride, the bride serves coffee. It denotes respect and significance...  

Paul's coffee story is a play on that. But they say it is even better, 41 years :) 

(I am not going to add any pictures, just to see if it will work ...)

**Comment by bilalyasar** [comment]
Thanks for the report, I will handle it

**Comment by atakanarikan** [comment]
This should be ok now. You can check it.
