### ISSUE TITLE
500 error on log out

### ISSUE THREAD

**Issue by bulenthacioglu** [bounswe/bounswe2015group7#215]
When I try to log out from my profile page, error page comes up. Here is the screenshot:

<img width="907" alt="ekran resmi 2016-01-06 13 26 15" src="https://cloud.githubusercontent.com/assets/11859322/12141696/6c90bf46-b47a-11e5-93b0-18217c193e64.png">

**Comment by atakanarikan** [comment]
Thanks for the issue, it's fixed.

Will be available after deploy.
