### ISSUE TITLE
Video presentation should be completed

### ISSUE THREAD

**Issue by narinmahmuti** [bounswe/bounswe2015group7#224]
Hey guys! Quick reminder of our final task this semester as a team (so sad!), we still have to finish the video that presents our work. 
Our video should address:
The main purpose of the application
Main requirements
Any differentiating properties
Demo of use cases (context appropriate)
Technologies
Your team (Who are you?)

Due date: 13.1.2016 @ 10 AM.
Max duration: 10 minutes

**Comment by narinmahmuti** [comment]
@atakanarikan @gmzrmks

**Comment by atakanarikan** [comment]
https://youtu.be/RiRdkJOlpdA
