### ISSUE TITLE
Project plan

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#42]
Prepare your project plan. You are required to use the ProjectLibre tool (http://www.projectlibre.org). The related course slides can be found in the Lecture Notes post.

Deadline: April 27th, Monday, 9:00 AM

**Comment by muratcakmak** [comment]
[[Project Plan | Project-Plan]] is added.

**Comment by muratcakmak** [comment]
Closed via [Project Plan](../wiki/Project-Plan)
