### ISSUE TITLE
Creating maven project with JUnit framework

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#43]
For assignment 8, we should write some functions and their corresponding JUnit function. Thus we should create an base project.
The project should consist JUnit framework. The framework will be included with Maven.
After base project is created, empty MathematicalOperations.java class and empty TestMathematicalOperations.java class for JUnit should be created.

**Comment by fthdgn** [comment]
Verified

**Comment by bilalyasar** [comment]
closed via https://github.com/bounswe2015group7/bounswe2015group7/commit/88ffdec9324e946d2c232bec7efe788195213747
