### ISSUE TITLE
Writing functions functions and their test functions

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#44]
This issue should be completed after issue #43 completed.

For assignment 8, each of us should write and commit a java function that performs a unique mathematical operation on MathematicalOperations.java file. (examples listed in: 
http://julia.readthedocs.org/en/latest/manual/mathematical-operations/).

After writing this functions, each of us should write and commit a JUnit test function containing at least 2 different fringe case tests for the function you wrote in MathematicalOperations.java (i.e. division by zero test for division). A nice tutorial can be found on http://www.vogella.com/tutorials/JUnit/article.html.

The deadline of this issue is May 4th 8:00.

**Comment by fthdgn** [comment]
Binary Minus operation and its test has written via 0cc62d5765678a90f30bf366940814f55eddbe13

**Comment by muratcakmak** [comment]
Inverse Divide function and its tests are added via 22fa67e92cb49163c3e355609eeac7d71e55d505

**Comment by ceenk** [comment]
Remainder function and its tests are added.

**Comment by bilalyasar** [comment]
added test binaryPlus via https://github.com/bounswe2015group7/bounswe2015group7/commit/88ffdec9324e946d2c232bec7efe788195213747

**Comment by mustafafeyzioglu** [comment]
Absolute function and its tests are added
