### ISSUE TITLE
Documenting code

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#45]
This issue should be completed after issue #44 completed.

For assignment 8, each of us should document our mathematical operation functions and test functions using doxygen format.

Deadline of this issue is May 7th 23:59

**Comment by muratcakmak** [comment]
I think this is issue should be divided into two.

**Comment by fthdgn** [comment]
OK, I will divide it in two.

**Comment by muratcakmak** [comment]
Thanks

**Comment by bilalyasar** [comment]
seems all java classes are well documented: see more here: https://github.com/bounswe/bounswe2015group7/blob/master/src/main/java/MathematicalOperations.java
