### ISSUE TITLE
Responsibility Assignment Matrix

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#47]
We should create a responsibility assignment matrix for our project.

**Comment by muratcakmak** [comment]
I think we can use spreadsheet of google docs. It is a efficient tool to create a RAM.

**Comment by muratcakmak** [comment]
https://docs.google.com/spreadsheets/d/1biMvFQmJGVt297n0LRSDjH-5QvlvTfO8wMHugTnIqUI/edit?usp=sharing

**Comment by fthdgn** [comment]
@muratcakmak could you give me permission to edit the spreadsheet file?

**Comment by muratcakmak** [comment]
Anyone has the link has the right to edit the document now.

**Comment by muratcakmak** [comment]
wiki page for RAM is created and its link is added to the wiki list. In the future, it may be change due to human resource and the customer's demand.

**Comment by fthdgn** [comment]
Closed via [Responsibility-Assignment-Matrix](../wiki/Responsibility-Assignment-Matrix)
