### ISSUE TITLE
Entering the meeting notes and making the actual changes about yesterday's meeting

### ISSUE THREAD

**Issue by atakanarikan** [bounswe/bounswe2015group7#61]
Irem if you don't have the time I can do it, just let me know :)

**Comment by atakanarikan** [comment]
Actually I think Narin was going to do the changes, can you just write the meeting notes on the wiki page? Thanks

**Comment by gmzrmks** [comment]
I will write the meeting notes, no problem.

**Comment by narinmahmuti** [comment]
Changes from yesterday's meeting have been made to the requirements page as well.
