### ISSUE TITLE
Implementing API for story creation

### ISSUE THREAD

**Issue by bulenthacioglu** [bounswe/bounswe2015group7#78]
Following login&register api and documentation for story creation, we shall start with Narin and İrem.

**Comment by bulenthacioglu** [comment]
@gmzrmks  @narinmahmuti

**Comment by fthdgn** [comment]
The name of the cloud function is "story_create"
Request structure:
{
"title" : "mytitle",
"content" : "myContent",
"tags" : ["tag1","tag2"]
}

The response is Story object on Parse.
There is also custom errors which explain the problem.

Closed via 799f7f99e1c793e598cf4b7f7b538b7f1b650299
