### ISSUE TITLE
Research android unit testing & writing unit tests

### ISSUE THREAD

**Issue by narinmahmuti** [bounswe/bounswe2015group7#89]
We should research on the topic to be able to write some unit tests for our project. A good place to start is the link below:
http://futurice.com/blog/android-unit-testing-in-android-studio-and-ci-environments

**Comment by narinmahmuti** [comment]
@bulenthacioglu

**Comment by fthdgn** [comment]
We should use Espresso instead of Robolectric. Espresso is official UI testing framework of Android. I have added an example UI test on current Android project.Also I have written how to run it from command line on READ.ME of Android project.
